apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: beersapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:   
  rules:
  - host: mybeerstore.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 80