apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapi
spec:
  template:
    metadata:
      labels:
        app: beers
        component: webapi
    spec:
      containers:
      - name: webapi
        image: myrepodemo.azurecr.io/webapi
        imagePullPolicy: Always
        env:
        - name: ConnectionString
          value: Server=sql-data;Database=BeersDb;User Id=sa;Password=Pass@word
        ports:
        - containerPort: 80         
      imagePullSecrets:
      - name: acr-auth
---